import { StyleSheet } from 'react-native-unistyles'

export const styles = StyleSheet.create((theme) => ({
  root:                 { flex: 1, backgroundColor: theme.colors.background, paddingHorizontal: theme.spacing.lg },
  scroll:               { flex: 1 },
  inner:                { gap: theme.spacing.lg, paddingBottom: theme.spacing.xxl },
  header:               { gap: theme.spacing.sm, marginTop: theme.spacing.lg },
  title:                { color: theme.colors.text, fontSize: theme.typography.xxl, fontWeight: '700' },
  subtitle:             { color: theme.colors.muted, fontSize: theme.typography.base },
  card:                 { borderRadius: theme.radius.xl, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, padding: theme.spacing.lg, gap: theme.spacing.lg },
  cardTitle:            { color: theme.colors.text, fontSize: theme.typography.lg, fontWeight: '700' },
  gap:                  { gap: theme.spacing.sm },
  configuredRow:        { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm, backgroundColor: theme.colors.success, borderRadius: theme.radius.md, padding: 12 },
  configuredText:       { color: theme.colors.accentText, fontSize: theme.typography.sm, fontWeight: '600' },
  linkRow:              { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm, paddingVertical: 4 },
  linkText:             { fontSize: theme.typography.sm, fontWeight: '500' },
  hint:                 { color: theme.colors.muted, fontSize: theme.typography.xs },
  fieldGroup:           { gap: theme.spacing.sm },
  fieldLabel:           { color: theme.colors.muted, fontSize: theme.typography.sm, fontWeight: '500' },
  input:                { backgroundColor: theme.colors.surfaceAlt, borderWidth: 1, borderColor: theme.colors.border, borderRadius: theme.radius.md, paddingHorizontal: 12, paddingVertical: 8, color: theme.colors.text, fontSize: theme.typography.sm },
  divider:              { height: 1, backgroundColor: theme.colors.border },
  toggleRow:            { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  toggleTextGroup:      { flex: 1, gap: 2, paddingRight: theme.spacing.lg },
  toggleLabel:          { color: theme.colors.text, fontSize: theme.typography.base },
  footer:               { flexDirection: 'row', gap: theme.spacing.sm, borderTopWidth: 1, borderTopColor: theme.colors.border, paddingTop: theme.spacing.lg },
  footerBtn:            { flex: 1, alignItems: 'center', paddingVertical: 12, borderRadius: theme.radius.md },
  footerBtnPrimary:     { backgroundColor: theme.colors.accent },
  footerBtnPrimaryText: { color: theme.colors.accentText, fontSize: theme.typography.sm, fontWeight: '600' },
  footerBtnSecondary:   { backgroundColor: theme.colors.surfaceAlt, borderWidth: 1, borderColor: theme.colors.border },
  footerBtnSecondaryText:{ color: theme.colors.text, fontSize: theme.typography.sm, fontWeight: '600' },
}))
